### ISSUE TITLE
Feature Request: Allow remote intiface connections akak: allow intiface host/port to be specified

### ISSUE THREAD

**Issue by isaacclarke80** [UncensorPat/prohe#2]
I'm on a Windows machine developing in a Linux VM and would like to use PROHE. However, the project I'm working in only runs in Linux and so I have the project workspace open over SSH: for extensions to work they need to be installed in the remote extension host. However, PROHE is hard-coded to connect to [ws://localhost:12345](https://github.com/UncensorPat/prohe/blob/main/src/extension.ts#L110) .

Would it be possible to make the websocket connection host and port configurable  so people can set ws://10.123.45.67:46564 if necessary for this sort of situation?

**Comment by UncensorPat** [comment]
Thanks for the suggestion @isaacclarke80 - this should be a fairly trivial change to make the host string configurable. To be honest I meant to do it in my original configuration but completely forgot 😅 Will look to do this soon!

**Comment by UncensorPat** [comment]
Fixed in 055448c8cf8804a9106ffc8a34e2e4d8138fcf68, released in 0.1.0. Let me know if you have any issues with the new feature!
